### ISSUE TITLE
扫码体验

### ISSUE THREAD

**Issue by WsmDyj** [dwqs/mp-jithub#2]
这个是怎么实现的呢

**Comment by dwqs** [comment]
问题能否具体点？

**Comment by WsmDyj** [comment]
就是readme.md那个二维码怎么实现的

**Comment by dwqs** [comment]
这个是小程序发布上线之后，会有对应的二维码的

**Comment by WsmDyj** [comment]
你的数据怎么来的

**Comment by dwqs** [comment]
数据来自 github    趋势榜是爬虫爬的  其它是 [调用 github 的接口](https://developer.github.com/v3/) 获取的，因为 github 是国外域名，所以你要自己申请一个国内的备案域名作代理
