### ISSUE TITLE
npm run dev之后在dist目录下没有生成app.json等文件

### ISSUE THREAD

**Issue by shiqikai** [dwqs/mp-jithub#4]
npm run dev之后在dist目录下没有生成app.json等文件

**Comment by shiqikai** [comment]
![image](https://user-images.githubusercontent.com/10249745/50401975-aafe6680-07cd-11e9-900f-42ab1701fbde.png)

**Comment by shiqikai** [comment]
![image](https://user-images.githubusercontent.com/10249745/50402475-f581e200-07d1-11e9-8ce8-cc065c5deae0.png)

**Comment by shiqikai** [comment]
是不是src/下面的app.json文件没传啊？

**Comment by dwqs** [comment]
微信开发者工具打不开吗？我这一直是可以的啊

**Comment by shiqikai** [comment]
![image](https://user-images.githubusercontent.com/10249745/50437286-1fe3b480-0924-11e9-99ca-397eb4386385.png)
按照步骤生成的dist目录一直是这样，是不是src/下面的app.json文件没传啊？

**Comment by dwqs** [comment]
@shiqikai mpvue 不会自动生成 app.json 了 https://github.com/Meituan-Dianping/mpvue/issues/1273 需要开发者手动配置

配置 app.json 示例： https://github.com/mpvue/mpvue-quickstart/blob/master/template/src/app.json

**Comment by shiqikai** [comment]
![image](https://user-images.githubusercontent.com/10249745/50438599-9c2cc680-0929-11e9-84bf-e65d9b7b968d.png)
我增加添加过app.json也没用。 你看我之前的dist目录图片，用微信工具打开就是这样子

**Comment by dwqs** [comment]
把 dev 的脚本改成如下试试：

```
npx rimraf dist && npx cross-env NODE_ENV=development node ./build/dev-server.js && cp src/app.json ./dist
```

**Comment by shiqikai** [comment]
还是没用噢。我这边微信开发工具能打开的正常项目结构如下图所示， 对比上图，还是不一样的。你那边的dist目录能给我看看嘛?
![image](https://user-images.githubusercontent.com/10249745/50438948-1f025100-092b-11e9-8bd5-e11e41efa8ea.png)

**Comment by dwqs** [comment]
![image](https://user-images.githubusercontent.com/7871813/50439731-08112e00-092e-11e9-9d74-ee5e1d733388.png)

那你 run dev 之后 手动 copy app.json 到 dist 目录下吧

**Comment by shiqikai** [comment]
还是不行   是不是要配置webpack啥的？     快放弃了 心碎啊

**Comment by dwqs** [comment]
不需要
